#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.m$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    "uncrustify" -c "${REPO_ROOT_DIR}/uncrustify.cfg" --no-backup "$files" &>/dev/null
    git add $(echo "$files" | paste -s -d " " -)
fi
